services:
  app-prod:
    container_name: mu-digital-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "${HOST_IP}:8080:4000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=4000
    restart: always